baseURL: https://halimess.github.io/
languageCode: en-us
title: halimess 개발 블로그
theme: "PaperMod"

enableEmoji: true
enabledRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-76JEWQFRMR

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: 아무 글
  description: "내가 보려고 작성한 글"
  keywords: [Blog, Portfolio, PaperMod]
  author: halimess
  # images: 
  DataFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  disableSpecial1stPost: false
  disableScrollTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to diable highlight.js
    # disableFingerprinting: true
    # favicon: 
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  
  label:
    text: "halimess"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link
  
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    # - identifier: github
    #   name: github
    #   url: https://github.com/halimess
    #   weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
